### PR TITLE
Issue #29: Create a RELATED.md to list similar projects and SIGs

### PR DESCRIPTION
**Pull request by mik0w**
Hello, I've created a list of projects and SIGs similar to OWASP Top10 for ML Security. I don't know what is a suggested format, but I think I've included the most renowned resources regarding AI/ML security. 

Related issue: https://github.com/OWASP/www-project-machine-learning-security-top-10/issues/29

### CODE REVIEW

**Comment by sagarbhure** [comment]
This is great! Thanks.
- Would it be better if we structure these into categories for ex: usescases/domain/industry.
- A description summary etc..

This would help to unify the effort of all the initiatives and mapping it to respective practitioners(ML/Data/Infra/Ethical/Privacy) can refer to the correct standard w.r.t their usecases.

Open to suggestions.

**Comment by mik0w** [comment]
@sagarbhure Thanks for suggestions - I will update this PR later :)

**Comment by axsaucedo** [comment]
+1 this is great!

**Comment by shsingh** [comment]
Hi @mik0w as discussed let's push this merge through for now, then we can amend, add to it. It's a good start

**Review by shsingh — APPROVED** [review]
We will need to add into sections of:

Related OWASP
Related SIGs elsehwere

Then over time a section per persona, e.g. MLOps links, MLEng links, etc...

**Review by sagarbhure — APPROVED** [review]

**Pull request merged**
