### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by NextGenSec-Github**
Fixed typo in ML04_2023-Membership_Inference_Attack
Found under ML04_2023-Membership_Inference_Attack > Risk Factors > Threat Agents/Attack Vectors

### CODE REVIEW

**Review by shsingh — APPROVED** [review]

**Comment by shsingh** [comment]
thanks @NextGenSec-Github !

/cc @sagarbhure

**Comment by shsingh** [comment]
Hi @NextGenSec-Github ... are you please able to resubmit this as a signed commit? Information available here: https://github.com/OWASP/www-project-machine-learning-security-top-10/blob/master/CONTRIBUTING.md#github-information

**Comment by NextGenSec-Github** [comment]
Hey shsingh

Sorry about the confusion with my recent commits. I got confused and messed up with the signing requests. I've reforked the repo and resubmitted my fix, and i believe the commit should be signed and properly work this time. My apologies.

**Comment by shsingh** [comment]
Hi @NextGenSec-Github ,

Not a problem at all and please don't apologise. You're taking the time to contribute so I wanted to thank you.

FYI, we do signed commits not for security, but more as a way to attribute the commits to people.

**Pull request closed without merging**
