### PR TITLE
fix ePUB Renders.

### PR DESCRIPTION
**Pull request by msnishanth9001**
this PR contains fix to #99 and #128 

1. Workflow to automate mirror to the https://mltop10.info/ host GitHub repo.
2. Fixes MD files, so the ePUB renders without errors.
3. Fixes alignment of tables.

note, the data in table arrangement is not good so the ePUB variant has jumbled data. This can be revisited once the tabular data is fixed.

### CODE REVIEW

**Comment by shsingh** [comment]
> this PR contains fix to #99 and #128
> 
> 1. Workflow to automate mirror to the https://mltop10.info/ host GitHub repo.
> 2. Fixes MD files, so the ePUB renders without errors.
> 3. Fixes alignment of tables.
> 
> note, the data in table arrangement is not good so the ePUB variant has jumbled data. This can be revisited once the tabular data is fixed.

Hi @msnishanth9001 thanks for the PR.

Is the intent of this PR to mirror or to fix formatting issues? Or both?

At this stage the repo for https://mltop10.info is done manually because it needs a manual run of 'quarto' to generate the files. 

The rendering of EPUB and PDF at this stage is more critical then worrying about the mirroring portion IMHO.

**Comment by msnishanth9001** [comment]
Hi @shsingh 
The intent is to do both fix mirror and formatting issues. Once the formatting issue is fixed the ePUB generation will be fixed.

the following WF PR will publish ePUB and PDF.
- https://github.com/mltop10-info/mltop10.info/pull/4

**Comment by msnishanth9001** [comment]
updated to remove WF for mirror now.

**Comment by shsingh** [comment]
Hi @msnishanth9001 as your change is only for the _quarto.yml file did you want to add that as a PR to the mltop10-info repo instead?

The _quarto.yml file is not contained under docs/ in this project repository

**Comment by msnishanth9001** [comment]
was using it to test the renders, forgot to remove. Done now.

**Comment by shsingh** [comment]
Hi @msnishanth9001,

The files look like they have gone back to cfc455f7b7cb8cdac19e46d2321090e9085f619c

Will they work properly on both the OWASP site as well as render PDF on https://mltop10.info site?

**Comment by msnishanth9001** [comment]
>> The files look like they have gone back to https://github.com/OWASP/www-project-machine-learning-security-top-10/commit/cfc455f7b7cb8cdac19e46d2321090e9085f619c

- I have rebased the commit.

>> Will they work properly on both the OWASP site as well as render PDF on https://mltop10.info/ site?

- yes. https://mltop10.info/ site needs this PR integrated. https://github.com/mltop10-info/mltop10.info/pull/6.
- ePUB to verify ePUB render on my fork. > https://github.com/msnishanth9001/mltop10.info/blob/epub-fixes/docs/OWASP-Machine-Learning-Security-Top-10.epub

**Comment by shsingh** [comment]
Hi @msnishanth9001 I am not sure what is being commited in this PR anymore as the files only show the GH issues. Are please you able to see if you can send another PR with the proposed changes you had?

**Pull request closed without merging**
